############
## Stages
############
stages:
  - test

############
## Testing
############
test_lab:
  stage: test
  script:
    # - apt-get update -qy
    # - apt-get -y upgrade
    # - python3 -V
    # - apt-get install -y python3-pip
    # - apt-get build-essential libssl-dev libffi-dev python-dev
    # - pip3 install pipenv
    # - pipenv install
    # - pipenv run python Aufgabe1/clientserver_test.py
    - which python
    - python --version
  tags:
    - debian